[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wation"
version = "2.0.10"
description = "This package provides a connector to interact with the services of wation.net"
readme = "README.md"
requires-python = ">=3.5"
authors = [
    { name="Wation", email="Github@Wation.net" }
]
license = { text="MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "appdirs",
    "requests",
    "cryptography"
]

[project.urls]
Homepage = "https://github.com/TheWation"

[project.scripts]
wation = "wation.cli:main"