[tool.poetry]
name = "microservice-story-manager"
version = "0.2.0"
description = "Microservice Story Manager is a Python library for optimizing user story assignments in microservice architectures. It features story and microservice management, genetic algorithm optimization, and visualization tools. The library calculates metrics like coupling and cohesion, allows comparison of optimization strategies, and supports CSV data loading. It aids in microservice design decisions, helping maximize cohesion and minimize coupling in software architectures."
authors = ["radix1001 <luis@thedogcompany.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
networkx = "^3.3"
matplotlib = "^3.9.1"
deap = "^1.4.1"
mpld3 = "^0.5.10"
spacy = "^3.7.5"
jupyter = "^1.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.5.2"

[tool.ruff]
select = ["E", "F", "I"]
ignore = []
line-length = 120

[tool.ruff.isort]
known-first-party = ["microservice_story_manager"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
