[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moveread-dfy"
version = "0.1.34"
authors = [
  {name="Marcel Claramunt", email="marcel@moveread.com"}
]
description = "Moveread DFY data models and API"
dependencies = [
  "lazy-loader", "pydantic", "dslog",
  "sqlmodel", "sqltypes", "python-kv[azure]",
  "chess-scraping", "chess-pairings", "chess-utils"
]
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

[project.urls]
repo = "https://github.com/moveread/moveread-dfy.git"

[project.optional-dependencies]
server = ["pure-cv", "fastapi", "python-multipart", "uvicorn[standard]", "python-kv[azure]", "psycopg2-binary", "dslog"]
clientgen = ["openapi-ts"]

[project.scripts]
dfy-api = "moveread.dfy.server.cli:main"
dfy-clientgen = "moveread.dfy.server.clientgen_cli:main"
dfy-doer = "moveread.dfy.doer.cli:main"