[project]
name = "tflump"
description = "TfL API access and analysis in python"
authors = [
    { name = "pilchard", email = "187820+pilchard@users.noreply.github.com" },
]
readme = "README.md"
requires-python = ">= 3.8"
license = { text = "MIT" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "httpx>=0.27.0",
    "pydantic>=2.8.2",
    "pydantic-settings>=2.3.4",
    "pandas>=2.2.2",
    "ipykernel>=6.29.5",
    "folium>=0.17.0",
    "numpy>=2.0.0",
    "seaborn>=0.13.2",
    "geopandas>=1.0.1",
    "ipywidgets>=8.1.3",
]
dynamic = ["version"]

[project.urls]
homepage = "https://pilchard.github.io/tflump/"
documentation = "https://pilchard.github.io/tflump/"
repository = "https://github.com/pilchard/tflump"

[project.optional-dependencies]
dev = ["pytest", "importlib_resources"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "src/tflump/__init__.py"

[tool.rye]
managed = true
dev-dependencies = ["mypy>=1.10.1", "pytest>=8.2.2"]

[tool.hatch.build.targets.wheel]
packages = ["src/tflump"]

[tool.ruff]
include = ["pyproject.toml", "src/tflump/**/*.py", "scripts/**/*.py"]
src = ["src"]


[tool.ruff.lint]
select = ["ALL"]
unfixable = ["F401"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 80

[tool.ruff.lint.pydocstyle]
convention = "numpy"
