[tool.poetry]
name = "dcs-cli"
version = "0.3.111"
description = "SDK for DataChecks"
authors = ["Waterdip Labs <hello@waterdip.ai>"]
readme = "README.md"
packages = [{ include = "dcs_cli" },{ include = "data_diff" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pydantic = ">=1.10.12"
click = ">=8.1"
rich = "*"
toml = ">=0.10.2"
mysql-connector-python = {version=">=8.0.29", optional=true}
psycopg2 = {version="*", optional=true}
snowflake-connector-python = {version = ">=3.0.2,<4.0.0", optional=true}
cryptography = {version="*", optional=true}
trino = {version=">=0.314.0", optional=true}
presto-python-client = {version="*", optional=true}
clickhouse-driver = {version="*", optional=true}
duckdb = {version="*", optional=true}
keyring = "*"
tabulate = ">=0.9.0"
preql = {version=">=0.2.19", optional=true}
vertica-python = {version="*", optional=true}
urllib3 = "<2"
oracledb = {version = "*", optional=true}
pyodbc = {version=">=4.0.39", optional=true}
typing-extensions = ">=4.0.1"
attrs = ">=23.1.0"
mashumaro = {version = ">=2.9,<3.11.0", extras = ["msgpack"]}
pyyaml = "^6.0.1"

[tool.poetry.dev-dependencies]
parameterized = "*"
unittest-parallel = "*"
preql = ">=0.2.19"
mysql-connector-python = "*"
psycopg2 = "*"
snowflake-connector-python = ">=3.0.2,<4.0.0"
cryptography = "*"
trino = ">=0.314.0"
presto-python-client = ">=0.8.3"
clickhouse-driver = "*"
vertica-python = "*"
duckdb = ">=0.9.0"
ruff = ">=0.1.4"

[tool.poetry.extras]
# When adding, update also: README + dev deps just above
preql = ["preql"]
mysql = ["mysql-connector-python"]
postgresql = ["psycopg2"]
redshift = ["psycopg2"]
snowflake = ["snowflake-connector-python", "cryptography"]
presto = ["presto-python-client"]
oracle = ["oracledb"]
mssql = ["pyodbc"]
# databricks = ["databricks-sql-connector"]
trino = ["trino"]
clickhouse = ["clickhouse-driver"]
vertica = ["vertica-python"]
duckdb = ["duckdb"]
all-dbs = [
    "preql", "mysql-connector-python", "psycopg2", "snowflake-connector-python", "cryptography", "presto-python-client",
    "oracledb", "pyodbc", "trino", "clickhouse-driver", "vertica-python", "duckdb"
]


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
isort = "^5.13.2"
pre-commit = "^3.7.1"
flake8 = "^7.1.0"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry.scripts]
dcs_cli = 'dcs_cli.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"