[project]
name = "rooms_shared_services"
version = "0.0.2"
authors = [
  { name="kras55", email="dkras5577@gmail.com" },
]
description = "A package of shared services for rooms project"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/kras55/rooms_shared_services"
Issues = "https://github.com/kras55/rooms_shared_services/issues"


[tool.poetry]
name = "rooms_shared_services"
version = "0.1.221"
description = ""
authors = ["kras55 <dkras5577@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.9"
pydantic = "^2.5.2"
openai = "^1.35.3"
pydantic-settings = "^2.1.0"
backoff = "^2.2.1"
pyyaml = "^6.0.1"
more-itertools = "^10.2.0"
aws-lambda-powertools = "^2.40.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.23.2"
uvloop = "^0.19.0"
faker = "^22.1.0"


[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
add-trailing-comma = "^3.1.0"
isort = "^5.12.0"
pre = "^1.3.0"
flake8-pyproject = "^1.2.3"
pre-commit = "^3.5.0"
wemake-python-styleguide = "^0.18.0"
mypy = "^1.6.1"



[tool.poetry.group.boto3.dependencies]
boto3 = "^1.34.15"
mypy-boto3-dynamodb = "^1.34.0"
boto3-stubs = "^1.34.15"
aioboto3 = "^12.3.0"
types-aioboto3 = "^12.3.0"
mypy-boto3-s3 = "^1.34.64"
mypy-boto3-translate = "^1.34.0"



[tool.poetry.group.telegram.dependencies]
pytelegrambotapi = "^4.20.0"

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''


[tool.isort]
atomic = true
profile = "black"
line_length = 120
skip_gitignore = true
known_first_party = []
skip = []
