[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "figshare_driver"
version = "0.0.2"
authors = [
  { name="Cristian Garcia", email="cristian.garcia@ubiquitypress.com" },
]
description = "Functions required by the figshare-driver"
readme = "README.rst" 
requires-python = ">=3.10"
dependencies = [
  "pandas>=2.2.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
