[tool.poetry]
name = "vscode-project-cli"
version = "0.1.3"
description = ""
license = "MIT"
authors = ["Marco Carmona <marcocarmonadev@outlook.com>"]
readme = "README.md"
packages = [{ "include" = "source" }]


[tool.poetry.scripts]
vscode-project = "source.frameworks_and_devices.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
