[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "k_general_kit"
version = "1.1.0"
authors = [{ name = "KpihX", email = "kapoivha@gmail.com" }]
maintainers = [{ name = "KpihX", email = "kapoivha@gmail.com" }]
description = "A package with some usual general functions and objects"
readme = "README.md"
license = { text = "MIT License" }
requires-python = ">=3.8"
keywords = ["general", "containers", "tools", "search", "sort"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://pypi.org/project/k-general-kit/"
Issues = "https://github.com/KpihX/k_general_kit/issues"
Repository = "https://github.com/KpihX/k_general_kit.git"
