[tool.poetry]
name = "r3xa"
version = "2024.7.dev1"
description = "Remember, Reuse and Replicate eXperiments and Analyses"
authors = ["Emmanuel Roubin <emmanuel.roubin@univ-grenoble-alpes.fr>"]
maintainers = ["Emmanuel Roubin <emmanuel.roubin@univ-grenoble-alpes.fr>"]
homepage = "https://photomecanics.gitlab.io/r3xa/doc"
repository = "https://gitlab.com/photomecanics/r3xa"
keywords = []
readme = "README.md"
# license = "LICENSE"
classifiers = [
    "Natural Language :: French",
    "License :: Public Domain"
]
include = ["resources/schema.json"]

[tool.poetry.dependencies]
python = "^3.9"
jsonschema = "4.21.1"
python-slugify = "8.0.4"
Pygments = "2.17.2"
pyvis = "0.3.2"
PyQt5 = [
      {version = "=5.15.2", markers = "sys_platform == 'linux'"},
      {version = "*", markers = "sys_platform == 'win32' or sys_platform == 'darwin'"}
]

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
pytest = "8.1.1"
pre-commit = "3.5.0"
coverage = "7.4.4"
json-schema-for-humans = "0.47"
poethepoet = "0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
r3xa = "r3xa.scripts:script_gui"
r3xa-validate = "r3xa.scripts:script_validate"
r3xa-visualise = "r3xa.scripts:script_visualise"

[tool.poe.tasks]
# build html doc
doc_fold = "mkdir -p doc"
doc_json = "poetry run generate-schema-doc --config no_link_to_reused_ref --config copy_js --config no_collapse_long_descriptions --config no_collapse_long_examples resources/schema.json doc/index.html"
doc = ["doc_fold", "doc_json"]
# build coverage
cov_test = "poetry run coverage run -m pytest"
cov_html = "poetry run coverage html"
cov = ["cov_test", "cov_html"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
ignore_errors = true
omit = ["__init__.py", "tests/*"]
exclude_also = ["if __name__ == .__main__.:"]

[tool.coverage.html]
directory = "coverage"
