[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
profile = 'black'
skip_gitignore = true
src_paths = ['fast_minh']

[build-system]
requires = ['setuptools >= 61.0', 'cmake==3.28.1']
build-backend = 'setuptools.build_meta'

[project]
name = 'fast_minh'
version = '0.0.1'
requires-python = '>=3.8'
dependencies = [
    'scipy==1.10.1',
]

[project.optional-dependencies]
dev = [
    'pytest~=7.4.3',
    'black==23.12.1',
    'isort==5.13.2',
    'ruff==0.4.2',
    'datasketch==1.6.4',
]
examples = [
    'datasets==2.16.1'
]

[tool.setuptools]
include-package-data = true
