[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
name = "blocksets"
version = "0.1.12"
authors = [
  { name="Dave Budd", email="maildavebudd@gmail.com" },
]
description = "Python package for performing set type operations on any layout of discrete space in any dimension."
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE.md"}
keywords = ["intervals", "lattice", "sets", "pixels", "points", "dimension", "ranges", "orthogonal", "space", "grid"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/daveisagit/blocksets"
Documentation  = "https://blocksets.readthedocs.io/"
Issues = "https://github.com/daveisagit/blocksets/issues"
