[tool.poetry]
name = "weather-chatbot-phi3"
version = "0.1.8"
description = "An LLM Chatbot integrated with Open Weather API for Real-Time Weather Information."
authors = ["Vatsal Patel <vatsal1804@gmail.com>"]
license = "CC-BY-NC-SA-4.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
gradio = "^4.32.1"
requests = "^2.32.3"
llama-cpp-python = "^0.2.76"
transformers = "^4.41.2"
datasets = "^2.19.1"
huggingface-hub = "^0.23.2"
pytest = "^8.2.1"
tomlkit = "0.12.0"
langchain = "0.2.7"
langchain_community = "0.2.7"

[[tool.poetry.packages]]
include = "weather_chatbot"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
weather-chatbot-phi3 = "weather_chatbot.app:main"

[tool.poetry.dev-dependencies]
pyinstaller = { version = "^6.7.0", python = ">=3.8,<3.13" }
